### ISSUE TITLE
Request Features

### ISSUE THREAD

**Issue by MaGeBZz** [Jongye0l/JipperResourcePack#1]
Hey I just discovered this mod and think it got potential to be the best mod in ADOFAI tbh but I got some more ideas to implement eventually

- Options to configure where the things are displayed (especially good for bigger screens where the font is small etc)
- An option to see the checkpoints in a level on the top left maybe, so you could see I'm at checkpoint 7/23 for example (not all people clear levels like jipper so some wanna see it eventually like me :D)
- An option for a text like the checkpoints but for deaths in a run
- A way to change the text of something too (for example this here, probably it says "time" but for non-koreans they wanna change it eventually)
![image](https://github.com/user-attachments/assets/e9d765dd-1ccc-4285-af99-ebfb11947d34)
- KeyLimiter (only thing why I still have ADOFAI Tweaks)

**Comment by Jongye0l** [comment]
As a result of discussing with Jipper, we decided to add a size change, checkpoint, and text English support!
Thank you for Issue!

**Comment by MaGeBZz** [comment]
@Jongye0l appreciate it, if the keylimiter + deaths in a run (if you make a Checkpoint rum) could ne added too, that would be insane!

**Comment by Jongye0l** [comment]
keylimiter is excluded because it is far from a ResourcePack, and the number of deaths can already be checked by Judgment at the bottom.

**Comment by MaGeBZz** [comment]
Mh I think keylimiter fits really good into that and from the judgement you can only see the deaths in a "no death run" but not if you place checkpoints and die from them
